import React, { useState } from "react";
import { createRoot } from "react-dom/client";
import "./index.css";

function Header(){return <header className="bg-indigo-600 text-white shadow"><div className="mx-auto flex max-w-5xl items-center justify-between px-4 py-5 sm:px-6"><div><h1 className="text-2xl font-bold sm:text-3xl">Taskly</h1><p className="text-sm text-indigo-100">Simple To-Do List</p></div><span className="hidden rounded-full bg-white/15 px-3 py-1 text-xs font-medium sm:block">DCIT 26 • Laboratory 2</span></div></header>}
function TaskForm({taskText,setTaskText,onAdd}){const handleSubmit=e=>{e.preventDefault();onAdd()};return <form onSubmit={handleSubmit} className="flex flex-col gap-3 sm:flex-row"><input type="text" value={taskText} onChange={e=>setTaskText(e.target.value)} placeholder="Enter a new task..." aria-label="New task" className="min-w-0 flex-1 rounded-xl border border-slate-300 bg-white px-4 py-3 text-slate-800 outline-none transition focus:border-indigo-500 focus:ring-2 focus:ring-indigo-200"/><button type="submit" className="rounded-xl bg-indigo-600 px-5 py-3 font-semibold text-white transition hover:bg-indigo-700">+ Add Task</button></form>}
function TaskItem({task,onToggle,onDelete}){return <li className="flex flex-col gap-3 rounded-xl border border-slate-200 bg-white p-4 shadow-sm sm:flex-row sm:items-center sm:justify-between"><div className="min-w-0"><p className={`break-words font-medium ${task.done?"text-slate-400 line-through":"text-slate-800"}`}>{task.text}</p><span className={`mt-1 inline-block text-xs font-semibold ${task.done?"text-emerald-600":"text-amber-600"}`}>{task.done?"Done":"Not Done"}</span></div><div className="flex flex-wrap gap-2"><button type="button" onClick={()=>onToggle(task.id)} className={`rounded-lg px-3 py-2 text-sm font-semibold text-white ${task.done?"bg-amber-500 hover:bg-amber-600":"bg-emerald-600 hover:bg-emerald-700"}`}>{task.done?"Mark Not Done":"Mark Done"}</button><button type="button" onClick={()=>onDelete(task.id)} className="rounded-lg bg-rose-500 px-3 py-2 text-sm font-semibold text-white hover:bg-rose-600">Delete</button></div></li>}
function UserGuide(){return <section className="mt-6 rounded-2xl border border-indigo-100 bg-indigo-50 p-5 sm:p-6"><h2 className="text-lg font-bold text-slate-900">Instructions / User Guide</h2><ol className="mt-3 list-decimal space-y-2 pl-5 text-sm leading-6 text-slate-700"><li>Type your task and click <strong>Add Task</strong>.</li><li>Click <strong>Mark Done</strong> to complete a task. Click <strong>Mark Not Done</strong> to change it back.</li><li>Click <strong>Delete</strong> to remove a task.</li><li>Click <strong>Clear All</strong> to reset the task list.</li></ol></section>}
function App(){const [tasks,setTasks]=useState([]);const [taskText,setTaskText]=useState("");const addTask=()=>{const text=taskText.trim();if(!text)return;setTasks(current=>[...current,{id:Date.now(),text,done:false}]);setTaskText("")};const toggleTask=id=>setTasks(current=>current.map(task=>task.id===id?{...task,done:!task.done}:task));const deleteTask=id=>setTasks(current=>current.filter(task=>task.id!==id));const clearAll=()=>setTasks([]);const doneCount=tasks.filter(task=>task.done).length;return <div className="min-h-screen bg-slate-50 text-slate-900"><Header/><main className="mx-auto max-w-5xl px-4 py-8 sm:px-6 lg:py-10"><section className="rounded-2xl bg-white p-5 shadow-sm ring-1 ring-slate-200 sm:p-7"><div className="mb-6"><h2 className="text-2xl font-bold sm:text-3xl">My Tasks</h2><p className="mt-1 text-sm text-slate-500">Organize your tasks and keep track of what you have completed.</p></div><TaskForm taskText={taskText} setTaskText={setTaskText} onAdd={addTask}/><div className="mt-6 flex flex-col gap-3 border-b border-slate-200 pb-5 sm:flex-row sm:items-center sm:justify-between"><p className="text-sm font-medium text-slate-600">{tasks.length} {tasks.length===1?"task":"tasks"} • {doneCount} done</p><button type="button" onClick={clearAll} disabled={tasks.length===0} className="rounded-lg border border-slate-300 px-4 py-2 text-sm font-semibold text-slate-700 hover:bg-slate-100 disabled:cursor-not-allowed disabled:opacity-40">Clear All</button></div>{tasks.length===0?<div className="mt-6 rounded-xl border border-dashed border-slate-300 p-8 text-center"><p className="font-semibold text-slate-600">No tasks yet.</p><p className="mt-1 text-sm text-slate-400">Add your first task using the form above.</p></div>:<ul className="mt-6 space-y-3">{tasks.map(task=><TaskItem key={task.id} task={task} onToggle={toggleTask} onDelete={deleteTask}/>)}</ul>}</section><UserGuide/></main><footer className="border-t border-slate-200 bg-white py-5 text-center text-xs text-slate-500">DCIT 26 • Application Development and Emerging Technologies • Laboratory 2</footer></div>}
createRoot(document.getElementById("root")).render(<React.StrictMode><App/></React.StrictMode>);
